### ISSUE TITLE
Add support for masterlists

### ISSUE THREAD

**Issue by wlthomson** [wlthomson/ocsupply#17]
More of a discussion that an actual thing to implement at this stage.

Had a chat with @mark-prins about main requirements we want to demo. One of the big ones I hadn't thought much about was how to deal with normalised data, e.g. masterlists.

Using a relational model, we can have a many-to-many join, such that each masterlist can be joined to many items and many stores. Using a document approach, we would maybe do something like this:

```
// Store database

{
  items: [ { name, code }, ... ]
}
```

If we wanted to add an item to a masterlist, it would be quite tricky as we have no reference to the concept of a group of items. Next thought was something like this:

```
// Store database

{
  masterlists: [ 'masterlist_id', ... ]
}
```

```
// Masterlist database

{
  { 
    id: 'masterlist_id'.
    items: { name, code }, ... ] 
  }
}
```

So now we have added a sort of "foreign key", which to me feels like maybe I'm trying to think relationally, but I can't see an efficient alternative? A few things that I'm thinking about:

- Should these documents be in different databases, or am I trying to map databases to tables? 
- What about querying all the stores with a given masterlist, could map-reduce on the stores database, but would this be as efficient as querying a masterlist join table?

Any thoughts welcome, I think a good opportunity to do some more research into how to map relational problems to a document structure?

**Comment by joshxg** [comment]
Seems to be a few things here so will try to discuss each 

1. masterlists:

I'm confused why you don't just have 

`masterLists: { id, items: [ {id, name: ibuprogram}, {id, name: paracetemol } ] }`? 

2. Different databases

This is the slight annoyance of Couch DB imo and why I don't actually really like it to much. It's a proper document model. If you want to create 'collections',  we need to put a type field imo - `{type: "item"`}`, {type: "masterlist" }` and create views using the types

3. Querying all stores with a given master list

If this was actually a query we would use (why?), then you could create a view with the master list as the key, and each store as the value?

**Comment by wlthomson** [comment]
So, let's say we have:

```
masterLists: { id, items: [ {id, name: ibuprogram}, {id, name: paracetemol } ] }
```

The question I'm thinking of is a situation where you want to add an item to a masterlist. In that situation, you have to update every store document to add an item to that masterlist. If you do something like this:

```
masterlists: [ masterlist_id1, masterlist_id2, ... ]
```

You don't have the redundancy. 

So my question is, let's say we did want to know all stores with the HIV program. With a view, you would have to map over every store, and reduce to just the stores with the given master list. 

I can see this being questioned as less performant than, for example, querying for all masterlist-to-store joins with a given masterlist key.

Does that make sense?

**Comment by joshxg** [comment]
> The question I'm thinking of is a situation where you want to add an item to a masterlist. In that situation, you have to update every store document to add an item to that masterlist. If you do something like this:

I think this is just the nature of a non-sql database. It's not relational - using foreign keys is. I think your solution works and improves data integrity, but thats just not what no-sql is about. We can do performance enhancing techniques and help with data integrity, just like we can in sql (using a comma seperated string or a list field instead of a join table), when we need them, imo.

> So my question is, let's say we did want to know all stores with the HIV program. With a view, you would have to map over every store, and reduce to just the stores with the given master list.

Yup, it's not ideal, but from my understanding, you create views which will have the initial map reduce which yeah, isn;t too performant, but after that it's quick. But it's more about planning and not running random arbitrary queries, but having planned out idea of what data you need to gather

**Comment by wlthomson** [comment]
@joshxg Yeah it definitely felt "relational" and wrong, what you said makes sense.

**Comment by wlthomson** [comment]
I think at this stage this isn't really a feature, more of just something I wanted to discuss. 

Going to go ahead and close, can always create another issue for this if we decide we need to implement masterlists!
