### ISSUE TITLE
Pass ports in args when starting servers

### ISSUE THREAD

**Issue by joshxg** [wlthomson/ocsupply#26]
Alter the apollo server and the web server to accept a port in the arg when running i.e. `node . 1000` to run it on port 1000. Have a default also.

This should hopefully make it easier to edit the init script to spawn new process' to start an apollo server and a web server when we spawn the couch db dockers. 

Also need to point the client to the correct graphql server.. I think just having a text field to enter the port will be the easiest way?

**Comment by wlthomson** [comment]
This should do the job, although could also forget about ports and just use docker to make a network with host mappings. That way the app itself doesn't need to handle any of the messy port mapping logic, it just needs to access the hosts it knows using the default ports for the service. The host mappings could perhaps be done through environment variables or by giving each container the appropriate `etc/hosts` file when they are spun up?

**Comment by joshxg** [comment]
I don't really know enough about docker to be doing much stuff - does that mean making new docker builds for all things? i.e the graphql server needs to know the couchdb port, the web server exposing a port for the client and the client to know the graphql server. This is all starting to take a bit longer then expected, so going with what I know at this point!

**Comment by wlthomson** [comment]
Nah, you can pass the environmental variables when you spin up the docker container (IIRC `-e`).

But I agree go with whatevers easiest!

**Comment by wlthomson** [comment]
Fixed by #23.
